name: Tests

on:
  workflow_call:
    # https://docs.github.com/en/actions/using-workflows/reusing-workflows
    inputs:
      python-version:
        required: false
        type: string
        default: '3.x'
      environment-url:
        required: false
        type: string

jobs:
  pypi-publish:
    name: Upload to PyPI
    environment:
      name: pypi
      url: ${{ inputs.environment-url }}
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ inputs.python-version }}
      - run: pdm publish
